language: java
jdk:
  - openjdk8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cheese;'

install: true

script: mvn install

services:
  - mysql

branches:
 only:
    - master

notifications:
  email:
    recipients:
      - cheese10yun@gmail.com