language: java
jdk:
  - openjdk8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cheese;'

install: true

script: mvn install

services:
  - mysql

branches:
 only:
    - master

after_success:
  - mvn clean cobertura:cobertura coveralls:report

notifications:
  slack: cheese-dev:JXKSTVY4wHsMPbJi2uoKtyxs