language: java
jdk:
  - openjdk8

branches:
 only:
    - master

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


notifications:
  email:
    recipients:
      - cheese10yun@gmail.com