spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cheese?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver