spring:
  profiles:
    active: local

# Local 환경
---
spring:
  profiles: local
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
    url: jdbc:mysql://localhost:3306/cheese?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

#security :
#  user:
#    name: user
#    password: test
#
#    oauth2:
#      client:
#        client-id: foo
#        client-secret: bar
security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
  user:
    name: user
    password: test
#    role: USER
logging:
  level:
    ROOT: DEBUG


spring.h2.console:
  enabled: true
  path: /h2-console

